finished CRUD operations with users
Pianissimo7/e-commerce pull request #8
Opened 2023-11-20 12:39 UTC by Pianissimo7

finished login, register and edit profile for users in the server

2023-11-20 14:04 UTC, Elon-Abulafia requested changes

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/.env
As a rule of thumb, never upload your `.env` file into your git repo.

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
>          self.password = password
This doesn't need to be in this file.

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
>      connection.close()
Consider moving the entire DB interaction logic to a class that handles the connection, cursor, etc... (in a different file)

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
>      return None
What exactly is `user[2]` or `*user[1:]`?
You shouldn't write code with magic numbers that don't mean anything.
Also every function should have just a single `return` statement.

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
> +    # Check if the new email is already in use by another user
Leaving comments in your code like that isn't recommended.
If you want to document your functions, leave docstrings at the definition of the function.

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
> +    # run the server
Again, pointless comment.

2023-11-20 14:04 UTC, Elon-Abulafia commented on backend/server.py
>          return error_response('email is already in use', 401)
Maybe try to handle logged in users in a different form.
This doesn't really work with multiple users.

2023-11-21 09:02 UTC, Pianissimo7 commented on backend/server.py
>          return error_response('email is already in use', 401)
this shouldnt be an issue and therefore havent been fixed

2023-11-21 09:04 UTC, Pianissimo7 commented
fixed all of the issues from the CR

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +db_config = {
You should have consts file where you will keep the DB host & Database

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +def get_user_by_email(email):
Create a DB connection class, singleton, and all the access methods will go through that class

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +    user = cursor.fetchone()
Check what happens when `fetchone()` returns nothing

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +    else:
`else` is redundent

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +def user_exists(email):
redundent

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +    existing_user = cursor.fetchone()
exists instead of fetchone(?)

2023-11-21 12:16 UTC, IdanPhilosoph commented on backend/database.py
> +    user_data = (name, email, password)
Not necessary

2023-11-21 12:16 UTC, Pianissimo7 commented on backend/server.py
>      user_data_json = request.get_json()
`get_json()` is deprecated, use `json()` instead.

2023-11-21 12:16 UTC, Pianissimo7 commented on backend/server.py
> +    user = get_user_by_email(login_data_json['email'])
change PK to id, email is expensive to work with as a PK

2023-11-22 20:04 UTC, merged